### ISSUE TITLE
OTP 18 support

### ISSUE THREAD

**Issue by optikfluffel** [ten0s/syntaxerl#8]
Hi :smile_cat: 

To be safe when pulling in [OTP18 for Homebrew](https://github.com/Homebrew/homebrew/pull/41035) we need to know that your syntax checker tool supports OTP18 or at least doesn't break using it. What's the current status on this?

Thanks :heart:

**Comment by ten0s** [comment]
Hi,

I added OTP R16B03-1, 17.5, 18.0 and launch syntaxerl after build to the travis-ci config.
Also xref was added. 

The tests went OK. It means is possible to build and run syntaxerl on all the above configurations.
I would say the smoke tests passed.

As I don't plan to use OTP 18 any time soon, this is all I can say right now. 

Thanks
