### ISSUE TITLE
Erros with -include_lib detection

### ISSUE THREAD

**Issue by feliperama** [ten0s/syntaxerl#9]
Hi guys,

I tried to use the syntaxerl at https://github.com/2600hz/kazoo, a relatively complex project, and noticed that all -include_libs are getting errors.

For example, at applications/callflows/src/callflow.hrl file, I got the following error in a vim+syntastic+sytaxerl enviroment:
    " can't find include lib "whistle/include/wh_types.hrl" [erlang/syntaxerl] 

I saw the same problem with vimerl, which also uses rebar.

**Comment by ten0s** [comment]
Hi there,

...
SyntaxErl uses the rebar config under the hood to determine deps and libs paths.
...

It's not possible to build this project with rebar and syntaxerl doesn't work as well.

Actually, I'm positive that it's possible to cook up some dummy rebar.config files with
deps and libs specified to make (at least part of) it work.
